### ISSUE TITLE
buidler fails to compile: evmVersion: "byzantium" and CREATE2 

### ISSUE THREAD

**Issue by shanejonas** [MolochVentures/moloch#32]
**Describe the issue**

Trying to compile the code errors on `CREATE2` since that is not enabled on byzantium. 

**Steps to Reproduce**
1. `npx buidler moloch-deploy --network develop`
2. See error below

**Error**

```
contracts/gnosis-safe/proxies/ProxyFactory.sol:50:22: Warning: The "create2" instruction is only available for Constantinople-compatible VMs. You are currently compiling for "byzantium", where it will be interpreted as an invalid instruction.
            proxy := create2(0x0, add(0x20, deploymentData), mload(deploymentData), salt)
                     ^------------------------------------------------------------------^

Error BDLR600: Compilation failed
```

**Additional Information**

https://github.com/MolochVentures/moloch/blob/1077f425ed92a44ab8906a3ca521ebe0214c0121/buidler.config.js#L40

**Comment by alcuadrado** [comment]
Hey @shanejonas! Which version/branch of the code are you using? `master`?

**Comment by shanejonas** [comment]
correct. master

**Comment by alcuadrado** [comment]
I can't reproduce it, I'm getting that as a warning, not an error. Can you post more info about your environment? Windows/Linux/Mac? Node version? Any modification to the buidler config?

**Comment by Npizza** [comment]
Where I can find more information about CREATE2?

**Comment by alcuadrado** [comment]
> Where I can find more information about CREATE2?

This is a nice article about it: https://blog.openzeppelin.com/getting-the-most-out-of-create2/

**Comment by Npizza** [comment]
Thank you!! You opened a new world to me :smile:

**Comment by WillSaveTime** [comment]
Thank you
