### ISSUE TITLE
Error while deploying a DAO

### ISSUE THREAD

**Issue by junedl-nimblechapps** [MolochVentures/moloch#37]
Im trying to deploy a new DAO and Im following instruction give on read.me

Here are the steps that I have followed.

- Cloned this library and installed the dependencies using `npm i`

- Then I edited  `buidler.config.js` and set values for `INFURA_API_KEY` and `MAINNET_PRIVATE_KEY`(account private key exported from metamask).

- Im keeping  `deployment-params.js` as it is.

- Now when I run  `npx buidler moloch-deploy --network mainnet` 

I'm getting following error.

![Screenshot 2019-11-06 at 4 43 52 PM](https://user-images.githubusercontent.com/39292328/68294488-56e33480-00b6-11ea-8d17-dd641540acb0.png)

what will be value of  `BuilderConfig.networks.develop.url`?

**Comment by alcuadrado** [comment]
Hi @junedl-nimblechapps,

This project used a beta version of Buidler. In version 1.x we renamed `develop` to `localhost`. I submitted a PR here upgrading Buidler and fixing the config. See #38

**Comment by junedl-nimblechapps** [comment]
Well It worked after upgrading the builder and fixing the config as suggested by @alcuadrado.

It deployed first time but when I tried again Im continuously getting this error.

![Screenshot 2019-11-15 at 12 02 54 PM](https://user-images.githubusercontent.com/39292328/68921831-f9c73d00-079f-11ea-87c0-6c0afd241cc1.png)
