### ISSUE TITLE
Error Deploying DAO

### ISSUE THREAD

**Issue by tylerehc** [MolochVentures/moloch#48]
npx buidler moloch-deploy --network mainnet
Compiling...
Downloading compiler version 0.5.3

contracts/Moloch.sol:505:46: Warning: This declaration shadows an existing declaration.
    function _ragequit(uint256 sharesToBurn, IERC20[] memory approvedTokens) internal {
                                             ^----------------------------^
contracts/Moloch.sol:89:5: The shadowed declaration is here:
    IERC20[] public approvedTokens;
    ^----------------------------^

contracts/gnosis-safe/proxies/ProxyFactory.sol:50:22: Warning: The "create2" instruction is only available for Constantinople-compatible VMs. You are currently compiling for "byzantium", where it will be interpreted as an invalid instruction.
            proxy := create2(0x0, add(0x20, deploymentData), mload(deploymentData), salt)
                     ^------------------------------------------------------------------^

contracts/GuildBank.sol:13:54: Warning: Unreachable code.
        for (uint256 i=0; i < approvedTokens.length; i++) {
                                                     ^-^

contracts/gnosis-safe/libraries/CreateAndAddModules.sol:12:27: Warning: Unused function parameter. Remove or comment out the variable name to silence this warning.
    function enableModule(Module module)
                          ^-----------^

contracts/gnosis-safe/libraries/CreateAndAddModules.sol:12:5: Warning: Function state mutability can be restricted to pure
    function enableModule(Module module)
    ^ (Relevant source part starts here and spans across multiple lines).

Compiled 35 contracts successfully
Deploying a new DAO to the network mainnet
Deployment parameters:
   summoner: 0xfA5f6c326692019A550f31C3655aBF1fa732bD4B 
   token: 0xa1b3de85197f26e78016ccb8ac36594e03bee494 
   periodSeconds: 17280 
   votingPeriods: 35 
   gracePeriods: 35 
   abortPeriods: 5 
   proposalDeposit: 1000000000000000000 
   dilutionBound: 3 
   processingReward: 10000000000 

? Please confirm that the deployment parameters are correct Yes
Deploying...
An unexpected error occurred: Returned error: Invalid JSON RPC response: "basic auth failure\n"

This shouldn't have happened, please report it to help us improve Buidler.
For more info run Buidler with --show-stack-traces.

**Comment by tylerehc** [comment]
Trying to deploy with a token I created. Is that possibly the issue?

**Comment by tylerehc** [comment]
I also get "something went wrong" when I try to deploy via DAOhaus

**Comment by alcuadrado** [comment]
Are you behind a proxy? This error message `An unexpected error occurred: Returned error: Invalid JSON RPC response: "basic auth failure\n"` indicates that your node is behind [http basic auth](https://en.wikipedia.org/wiki/Basic_access_authentication) and that that failed.

**Comment by tylerehc** [comment]
I'm running it locally. I didn't do anything to set up a proxy.

**Comment by alcuadrado** [comment]
Can you post the steps to reproduce it?

**Comment by tylerehc** [comment]
Look at it again, I believe I had the mainnet endpoint where only the mainnet key was needed. Probably not a common enough error to worry about giving a unique error message haha.

Upon revision, I get a new error. Normally I'd just trouble shoot these, but since it says to report them... I hope they're helpful!

New error:

An unexpected error occurred: expected array value (arg="_approvedTokens", coderType="array", value="0xa1b3de85197f26e78016ccb8ac36594e03bee494")

This shouldn't have happened, please report it to help us improve Buidler.

**Comment by alcuadrado** [comment]
Oh, so you were missing infura's access token? That's interesting. It's probably not that uncommon.

Your new error means that you are passing an address to an `_approvedTokens` param, which expects an array.

Thanks for reporting these.

**Comment by tylerehc** [comment]
I put the private token in the "INFURA_API_KEY" slot and the Mainnet URL in "MAINNET_PRIVATE_KEY"... silly mistake

I'm not sure what array it might be looking for. The instruction step says "You input the token address of the token you want to be used as the DAO pledge." I have input the contract address (0xa1b3de85197f26e78016ccb8ac36594e03bee494) from here: https://etherscan.io/token/0xa1b3de85197f26e78016ccb8ac36594e03bee494

I'm following a mixture of these instructions --> https://forum.metacartel.org/t/moloch-contract-deployment-walk-through/98 and the README on the git page.

**Comment by tylerehc** [comment]
If I wrap the token address in an array...
`['0xa1b3de85197f26e78016ccb8ac36594e03bee494'] `

Then I get 
```
An unexpected error occurred: Returned error: gas required exceeds allowance (9937819) or always failing transaction

This shouldn't have happened, please report it to help us improve Buidler.
```

**Comment by wswarren12** [comment]
You probably need to increase your gas limit. Because of the contract size you also need to turn on your the optimizer setting when compiling. Here's what my truffle config looks like for that: 

  // Configure your compilers
  compilers: {
    solc: {
      version: "0.5.1",    // Fetch exact version from solc-bin (default: truffle's version)
      docker: false,        // Use "0.5.1" you've installed locally with docker (default: false)
      settings: {          // See the solidity docs for advice about optimization and evmVersion
      optimizer: {
      enabled: true,
      runs: 200
      },
      evmVersion: "byzantium"
      }
    }

**Comment by ameensol** [comment]
This was helpful! I turned on the optimizer by default now. It should work with just `npm i` and `npm run test`.

**Comment by tylerehc** [comment]
Thanks!
