### ISSUE TITLE
Typo error ?

### ISSUE THREAD

**Issue by Sirlupinwatson1** [MolochVentures/moloch#56]
Hi , just to make sure, about the buidler.config.js 

Does it should be buidler.config.js or builder.config.js

**Comment by alcuadrado** [comment]
It should be `buidler.config.js`. The typo is on purpose.

**Comment by Sirlupinwatson1** [comment]
Sorry about this, i had answer myself already but i think i am too much enthusiasm today.

Thanks sir for your time, much appreciated.
