### ISSUE TITLE
Questions about Ragequit

### ISSUE THREAD

**Issue by wowoyinwei** [MolochVentures/moloch#67]
Evnet Ragequit is used in the _ragequit method, the first argument is msg.sender. I'm not sure if that's a problem, but if I call the ragekick method, it's not the member that's kicked out. The event seemed meaningless.If I analyzed the data from evnet alone, I wouldn't know who was kicked out.

**Comment by HeikoFisch** [comment]
Thank you!
This is still WIP, and in particular the events haven't been (fully) adapted yet to recent changes -- such as the addition of the `ragekick` functionality. In the particular instance you're referring to, `msg.sender` must indeed be replaced with `memberAddress`.
