### ISSUE TITLE
UpdatePeriod() should be constant cost instead of while loop

### ISSUE THREAD

**Issue by PhABC** [MolochVentures/moloch#9]
If cost of loop (plus cost for rest of transaction) exceeds block gas limit, none of the functions depending on updatePeriod() will be executable. Having a constant cost for this function would prevent this issue.

My quick ballpark guess on how long it would take before contract becomes unusable: ~159-177 days

Update currentPeriod -> 5k 
Update periods[currentPeriod] -> 40k (start & end)
Update pendingProposals -> average ~2.5k?

With block gas limit of 8m and periodDuration of 1 day, that's about 159-177 days before the contract is unusable. However, If storage costs are revised upward, it could be a lot less than 170 days.

Since `periodDuration` is "fixed" and since `endTime` and `startTime` are predictable, we can maybe have something like:

```solidity
function getPeriodTimes(uint256 period) public returns (uint256 startTime, uint256 endTime) {
      startTime = now.sub(period.mul(periodDuration));
      endTime = startTime.add(periodDuration);
      return (startTime, endTime)
}
```

Need to account for change in period duration but that should be relatively easy by adding some other variables. Basically, we need to change how the `updatePeriod()` function works such that it has a contant cost, or we run the risk of making the other functions not executable.

**Comment by PhABC** [comment]
Since `periodDuration` is "fixed" and since `endTime` and `startTime` are predictable, you can maybe have something like:

```solidity
function getPeriodTimes(uint256 period) public returns (uint256 startTime, uint256 endTime) {
      startTime = now.sub(period.mul(periodDuration));
      endTime = startTime.add(periodDuration);
      return (startTime, endTime)
}
```

Need to account for change in period duration but that should be relatively easy by adding some other variables. Basically, we need to change to change how the `updatePeriod()` function works such that it has a contant cost, or we run the risk of making the other functions not executable.

**Comment by PhABC** [comment]
Seems like it was fixed with https://github.com/MolochVentures/moloch/commit/eef41f3e4075ed929e97dd2ff133ef34f68dbe90 @ameensol ? If so, could close this issue

**Comment by ameensol** [comment]
Yes, I think it was originally fixed by https://github.com/MolochVentures/moloch/commit/eba246a4a3a41c00d6b6ce80a5915efe39ba6dd6
